### ISSUE TITLE
Relative URLs

### ISSUE THREAD

**Issue by kevinmickey** [mortada/pelican_javascript#2]
This seems to force an absolute url -- doesn't work with RELATIVE_URLS = True

**Comment by mortada** [comment]
@kevinmickey could you please provide a use case?

When specifying an external resource this does expect an absolute URL. However if the resource (either JS or CSS) is internal then this plugin assumes it's under `content/js` or `content/css`, so in that case the URLs are relative to those directories.

**Comment by kevinmickey** [comment]
Yes, I am talking about internal resources located in `content/js` or `content/css`.  With RELATIVE_URLS  = True, I run pelican and I see that pelican_javascript has added references to the resources to the correct files, but the references are absolute:

```
<link rel="stylesheet" href="www.mydomain.com/css/mystyle.css" type="text/css" />
```

Where SITEURL = "www.mydomain.com"

Or if SITEURL =""

```
<link rel="stylesheet" href="/css/mystyle.css" type="text/css" />
```

A relative URL should look like:

```
<link rel="stylesheet" href="css/mystyle.css" type="text/css" />
```

My particular use case is that I want to generate static output that I can use locally from its arbitrary filepath, rather than having to run pelican.server.

**Comment by mortada** [comment]
I see, what if we change the code as follows:

```
-                    link = "%s/%s/%s" % (site_url, dirnames[key], f)
+                    if site_url == '':
+                        # no need for starting slash if site_url is empty
+                        link = "%s/%s" % (dirnames[key], f)
+                    else:
+                        link = "%s/%s/%s" % (site_url, dirnames[key], f)
```

would this work for your use case? this wouldn't depend on `RELATIVE_URLS` though, so I'm not sure if this is what you have in mind.

**Comment by kevinmickey** [comment]
No, I expect the current behavior for SITEURL="" -- they are absolute urls with / as the domain.  Here's what I would want:

```
-                    link = "%s/%s/%s" % (site_url, dirnames[key], f)
+                    if gen.settings['RELATIVE_URLS']:
+                        link = "%s/%s" % (dirnames[key], f)
+                    else:
+                        link = "%s/%s/%s" % (site_url, dirnames[key], f)
```

This isn't perfect, but I'm not sure there is a perfect solution.  Namely, if you're calling for this metadata from some subdirectory (maybe pages, if those are in a subdirectory?), the relative url above (`css/mystyle.css`) will fail.  (In that case, it should be `../css/mystyle.css`).  That is, relative paths depend on the file calling them.  The "perfect" solution, if it exists, would be to call a function from the template rather than asking for a static property, and the function could adjust the relative url appropriately given the file that asked for it.

Side note: I'm also not sure if the slashes need to be OS-specific in a relative url, but I don't use Windows so I don't know.  I think it might still be okay -- looking around online, I do see some windows local urls that use / not \.

For the time being, the fix above is better than always using absolute urls, in my opinion.  Just add a note in the README that says: "Warning: If RELATIVE_URLS=True, right now only templates in your base directory will be able to retrieve the scripts or stylesheets.  Pelican docs recommend using absolute urls when publishing (http://pelican.readthedocs.org/en/3.6.3/settings.html#url-settings)"

**Comment by mortada** [comment]
I see, that makes sense. Since `RELATIVE_URLS` is only supposed to be used for local development I think it should be fine not being perfect. 

As for the OS path separator, there's `os.path.join` we could use that is OS-dependent. However in the case of HTTP links we do always want `/`, and in the case of local it is probably still ok for Windows as you noted.

**Comment by mortada** [comment]
I've committed this change, thanks! 

https://github.com/mortada/pelican_javascript/commit/58e7335e5f5fa0acc945425c2d12bf9dcadb150f
